# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

# This is the main docker-compose file for the sw360 environment. It configures
# the sw360 service and a couchdb and postgres that are required by sw360.
# Use it as described in README.md

version: '2'
services:

  sw360baseimage:
    build: ./sw360baseimage
    image: sw360baseimage
    command: /bin/true # just build the image and exit imediately when started

  sw360nginx:
    build: ./sw360nginx/
    image: sw360nginx
    restart: unless-stopped
    ports:
      - 8443:8443
    links:
      - sw360
    environment:
      - HOST=sw360
      - HOST_PORT=8080

  sw360:
    build:
      context: ./sw360/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - sw360baseimage
    image: sw360
    restart: unless-stopped
    links:
      - sw360postgres
      - sw360couchdb
    environment:
      - PROTOCOL=https
      - POSTGRES_USER=sw360
      - POSTGRES_HOST=sw360postgres
      - COUCHDB_HOST=sw360couchdb
      - COUCHDB_USER=sw360
    env_file: proxy.env
    extends:
      file: configuration.yml
      service: sw360

  sw360postgres:
    image: postgres
    restart: unless-stopped
    extends:
      file: configuration.yml
      service: sw360postgres
    environment:
      - POSTGRES_DB=sw360pgdb
      - POSTGRES_USER=sw360

  sw360couchdb:
    build: ./sw360couchdb/
    image: sw360couchdb
    restart: unless-stopped
    extends:
      file: configuration.yml
      service: sw360couchdb
    environment:
      - COUCHDB_USER=sw360
      - COUCHDB_LUCENE_HOST=sw360couchdb-lucene

  sw360couchdb-lucene:
    build:
      context: ./couchdb-lucene/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - sw360baseimage
    image: sw360couchdb-lucene
    restart: unless-stopped
    links:
      - sw360couchdb
    environment:
      - COUCHDB_HOST=sw360couchdb

